// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"hello/app"
	"hello/config"
	"hello/handler"
	"hello/route"
	"hello/server"
	"hello/service"
)

// Injectors from wire.go:

func InitializeApp() (app.App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return app.App{}, err
	}
	serverServer := server.NewServer(configConfig)
	serviceService := service.NewService()
	handlerHandler := handler.NewHandler(serviceService, serverServer)
	helloHandler := handler.NewHelloHandler(serviceService, serverServer)
	authHandler := handler.NewAuthHandler(serverServer)
	restrictHandler := handler.NewRestrictHandler(serverServer)
	routes := route.NewRoutes(serverServer, handlerHandler, helloHandler, authHandler, restrictHandler)
	appApp := app.NewApp(serverServer, routes)
	return appApp, nil
}
