// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"hello/app"
	"hello/handler"
	"hello/service"
)

// Injectors from wire.go:

func InitializeApp() app.App {
	serviceService := service.NewService()
	handlerHandler := handler.NewHandler(serviceService)
	appApp := app.NewApp(handlerHandler)
	return appApp
}
